base_url = "https://konceptosociala.eu.org/blog"
title = "koncepto sociala blog"
description = "Blog for Koncepto Sociala website"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true
theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/img/logo.svg"
theme = "dark"              # light, dark, auto, toggle
comment = true
fancy_code = true
dynamic_note = true # a note that can be toggled
h_anchor_link = true
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/home", url = "/", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
    { name = "/tags", url = "/tags", weight = 3 },
]

socials = [
    { name = "website", url = "https://konceptosociala.eu.org/", icon = "diaspora" },
    { name = "github", url = "https://github.com/konceptosociala/", icon = "github" },
    { name = "telegram", url = "https://t.me/ksociala_official", icon = "telegram" },
]